before_script:
  - docker info
  - cat /etc/hosts


stages:
  - py2
  - py3


py2-job:
  stage: py2
  script:
    - git clone https://github.com/DataBiosphere/toil.git && cd toil && virtualenv venv && . venv/bin/activate && make prepare && make develop extras=[all] && pip install htcondor && make test
    - pwd
    - sudo rm -rf tmp

py3-job:
  stage: py3
  script:
    - git clone https://github.com/DataBiosphere/toil.git && cd toil && virtualenv -p python3.6 venv && . venv/bin/activate && make prepare && make develop extras=[all] && pip install htcondor && make test
    - pwd
    - sudo rm -rf tmp
